server:
  port: 9305
spring:
  application:
    name: admin-client
#  boot:
#    admin:
#      client:
#        url: http://localhost:9301   # 配置admin-server的地址   结合了eureka等注册中心后，只需要注册到注册中心即可
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
logging:
  file: admin-client.log  # 添加开启admin的日志监控
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8085/eureka